// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmitzieacbcexvbyvugz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5taXR6aWVhY2JjZXh2Ynl2dWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMzYyNDQsImV4cCI6MjA1NDYxMjI0NH0.xfVTE7u7e1YAQCIqWz_Eildwzy7nm0DPszLnJ6SyYqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);